name: Auto deploy excalidraw
on:
  push:
    branches:
      - master

jobs:
  Auto-deploy-excalidraw:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Build Site
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
